### ISSUE TITLE
Rails - when to create an association vs when to create an attribute within an existing model?

### ISSUE THREAD

**Issue by benhawker** [makersacademy/slack-overflow#121]
This may well be the most general question ever asked on Slack Overflow (so I am not expecting an answer!) but here goes....

I wanted to ask about the wisdoms of when it is more appropriate to create a new model in rails and create an association with an existing model vs. adding attributes to an existing model from a design perspective but also performance.

For reference I am working on the following repo - https://github.com/benhawker/rails_marketplace - a buyer/seller marketplace built on Rails.

A fairly basic but more concrete example:
- A listing (I have a listing model) must have a category. I created a category model - making it easy to call category.listings and return all the listings within that category. The division of category seems to make sense as it's own model, and also allows further sub division and flexibility into sub categories if desired in the future.

- A listing must have a location. I am considering the idea of a location model - but also see other ways to filter by a location column that is on the listing table/model.

- A listing must have photos - again they can either sit 'on' the listing model directly or be associated via a separate photo model.

Taking a look at other Rails projects of a similar vein - this one is a good example https://github.com/Sphaerus/gumtree/tree/master/app/models I see that for a fairly straightforwards application the developer has created 15+ models to model the domain. My key question is, is this overkill?

I realise it depends on personal choice, emergent design, future flexibility vs. immediate development speed and many more factors but wanted to throw this out there to see whether one of the coaches could give their view on where a line may be drawn between these two options?

Thanks!

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by spike01** [comment]
Yup - a hugely vague question, but let me try to tackle it.

Let's look at Kent Beck's 4 rules of simple design. We want code that:

- Passes the tests
- Reveals intention
- No duplication
- Fewest elements

The repo you linked to fails on the very first rule, which makes talking about the rest difficult. Also, creating models for each type of field is kinda weird (and not very intension revealing), the fields are basically duplicates as they don't have any behaviour that differentiates them, and there are a lot more elements than are needed.

So, the code you've linked to is probably not a great example.

The things you've highlighted in the final paragraph are exactly what you need to be thinking about - by doing the simplest thing for now and having tests (so that you can safely refactor), you can add complexity to the system *if* and *only when* it's required. In the specific context of your app, your models seem sensible, although if categories are not currently not a necessary feature then I would recommend reading [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) - you can add them in later. 

Locations and photos could be a models, although if they are just a piece of incidental data (i.e. a link to a Google map or a photo) it might not need to be its own model. If they have more complex behaviour (in the case of photos, uploading, or that a location is an important part of you domain), then by all means break them out into models. 

As always, the answer is context specific! But I hope this has helped.

**Comment by benhawker** [comment]
Thanks Spike - certainly helps. Good to read more about Kent Beck's 4 rules of simple design - makes alot of sense.
