### ISSUE TITLE
How do I use a 'Let' statement with a double?

### ISSUE THREAD

**Issue by saratateno** [makersacademy/slack-overflow#139]
I think I roughly understand how the 'Let' statement works when using a double but can anyone help explain further how and when to use it?

Confused by the example from here:-
https://github.com/makersacademy/course/blob/master/boris_bikes/20_mocking_behaviour_on_doubles.md

```
# let's extract the double to a let
# statement so we can use it repeatedly
let(:bike) { double :bike }
it 'releases working bikes' do
  # let's superpower our double
  # using allow().to receive().and_return()
  allow(bike).to receive(:working).and_return(true)
  subject.dock double(:bike)
  bike = subject.release_bike
  # Now the double responds to working?
  # with the value true
  expect(bike).to be_working
end
```

From reading on the internet we think that 'Let' is a bit like setting a variable - except with a double, so that you can use the double throughout your tests. However, in the example it still continues using `double(:bike)` anyway????

**Comment by mechacoach** [comment]
Let is Rspec's efficient way of creating a variable. You could think of it as assigning a variable like normal, bike = double :bike. It's just slightly more memory-efficient.

**Comment by tansaku** [comment]
@saratateno the key thing with `let` is that it is lazy.  Basically the double will not be called into existence until the test actually references the bike.  Compare with the alternative `let!`:

https://www.relishapp.com/rspec/rspec-core/v/3-4/docs/helper-methods/let-and-let

**Comment by Willibaur** [comment]
Yes Sara, when you use `let(:bike) {double :bike}` what you are doing in effect is creating something similar to a variable with the difference that this is a "special variable" which you can modify to your own needs across your different tests.
You can set those parameters by using `allow().to receive().and_return()`.

I have found that the main issue with double is that we tend to forget the focus of the Class we are testing and because of that sometimes we do not know how to use our double, at least that was my experience.

Another point is that once `let` is created at the top of your `spec` you do not need to create a double again within your test eg. `brike = double(:bike)` you just either set your `allow` environment  and then you use your double bike, or use the short way `doubleName = double(:doubleName, methodName: returnValue, 2ndMethod: returnValue, ....)`, in that instance you do not require `let` and you can set more than method and return values if required.
