### ISSUE TITLE
November-2015 Afternoon standup time discussion

### ISSUE THREAD

**Issue by tansaku** [makersacademy/slack-overflow#140]
In the week 1 retro it was suggested that a 1:30pm afternoon standup time might work better.  There were some who preferred 1:30pm and others who seemed happy with 2:30pm.  This is up to you guys as a cohort to decide.

Please debate below in this Github issue and tell the coaches on Monday what you think you as a team would prefer.

One thing to consider is that given the current seniors have their standups at 1:30pm, then having yours at the same time makes it slightly more difficult for coaches to provide cover for each other if off sick etc., however we should be moving more and more to you running your own standups and needing less and less support from coaches to do so, so perhaps that's not a big deal ...

**Comment by michaellennox** [comment]
My opinion is that with the current time of 2:30 we effectively have a period between 12 and 3/3:15 where any potential coding time is drastically limited as it is very difficult to make any serious progress in dispersed 15 minute sessions if either of the pair partner wishes to partake in either the talks or meditation (like myself). By moving the sessions to 1:30 it would minimise downtime caused by small breaks.

**Comment by michaellennox** [comment]
... While still promoting he benefits that the talks / meditation provide

**Comment by Willibaur** [comment]
Well, what about to move stand ups at 1:00 then, in that way if someone wants to be in any lunch talk and meditation there will be no major time conflicts though.

**Comment by saratateno** [comment]
What about moving the time of meditation? 

I'd like the standups to be at 1.30pm (which allows a decent bit of code time in the morning and half an hour break for lunch). Time for coding after and then meditation (or yoga) happening mid-afternoon when your brain is slowing down! 

Also, it's difficult to do both yoga and meditation on the same day. So maybe yoga should come earlier in the day / be a lunchtime thing you can opt to do instead of going to a talk.

So it'd be something like this:-

09.30-10.15 Standup
10.15-12.00 Coding
12.00-13.30 Free choice of talk / yoga / lunch / more coding
13.30-14.15 Standup
14.15-16.00 Coding
16.00-16:30 Meditation
16.30-18:00 Coding

**Comment by spike01** [comment]
Ideally people would all do yoga AND meditation AND talks - there is huge value in all.

I'm always curious about people people constantly stressing about time - in the past year we have managed to cut between 2-3 hours of lectures a day from the schedule, we start 30 minutes earlier and people are STILL worried about not having enough time. You **need** downtime from your screens for the information to sink in and to allow your brain to come up with solutions (in my opinion and experience). Work smarter, not harder

**Comment by saratateno** [comment]
I want to do talks, meditation and yoga - but I wouldn't be doing all three of them on the same day. I definitely want to do at LEAST one of those every day... My suggestion above was with the objective of making more time to be able to fit them all in..
