### ISSUE TITLE
Random weather testing

### ISSUE THREAD

**Issue by tsetsova** [makersacademy/slack-overflow#159]
Hi everyone, I'm struggling with the design of a test - the plane shouldn't take off during a storm. The problem I'm facing is I need a landed plane to take off. If I set the weather to sunny for the plane to land, how do I set it to stormy afterwards to check it can't take off?

Here's my code

```
require_relative 'airplane.rb'
require_relative 'weather.rb'


class Airport
  attr_reader :planes

  DEFAULT_CAPACITY = 10

  def initialize(weather: Weather.new)
    @planes = []
    @storm = weather.stormy?
  end

  def set_capacity(capacity = DEFAULT_CAPACITY)
    @capacity = capacity
  end

  def planes
    @planes
  end

  def land(plane)
    raise 'This airport is full!' if full?
    raise 'Your flight has been delayed due to a storm' if @storm
    @planes << plane
    '#{plane} has landed.'
  end

  def take_off(plane)
    @planes.delete(plane)
    '#{plane} has taken off.'
  end

  private

  def full?
    @planes.count >= set_capacity
  end
end
```

```
require 'airport'

describe Airport do
  let(:plane) {double(:plane)}
  let(:weather) {double(:weather, stormy?: false)}
  subject { Airport.new(weather: weather) }

  it 'returns planes in the airport' do
    expect(subject.planes).to eq []
  end

  it 'sets a new capacity' do
    expect(subject.set_capacity(30)).to eq 30
  end

  describe 'landing' do

    it 'lands a plane' do
      expect(subject.land(plane)).to eq '#{plane} has landed.'
    end

    it 'stores the landed plane in the airport' do
      subject.land(plane)
      expect(subject.planes).to include plane
    end

     it 'raises an error if over capacity' do
      subject.set_capacity.times{subject.land(plane)}
      expect{subject.land(plane)}.to raise_error('This airport is full!')
    end
  end

  describe 'take-off' do

    before(:example) do
      subject.land(plane)
    end

    it 'plane takes off' do
      expect(subject.take_off(plane)).to eq '#{plane} has taken off.'
    end

    it 'removes the plane from the airport' do
      subject.take_off(plane)
      expect(subject.planes).to_not include plane
    end

    describe 'stormy weather take off' do

      it 'delays a flight if weather is stormy' do
        # allow(weather).to receive(:stormy?).and_return(true) <-- this doesn't work as expected
        expect{subject.take_off(plane)}.to raise_error('Your flight has been delayed due to a storm')
      end
    end
  end
end
```

It's the last test, all the other ones pass. Any help is greatly appreciated!! :)

**Comment by chweeks** [comment]
You could state in the test subject.planes = [plane], this ensures your only testing the take off method in your test without  relying on your land method to be working.

**Comment by ptolemybarnes** [comment]
Hey @tsetsova, I would guess that the problem originates in the order of execution. We want the order to be like this:

1. `allow(weather).to receive(:stormy?).and_return(true)` 
2. `subject { Airport.new(weather: weather) }`

But maybe it's happening the other way around?

**Comment by dearshrewdwit** [comment]
@tsetsova here's the answer I gave the other day.

It's looking good! A couple of things are going on that you may want to think about:

- if you initialise an Airport tightly coupled to a Weather object, how do you reset the `@storm` attribute? At the moment an Airport is created, weather is created, and the `@storm` is set. So in your design you can either land/take off planes or you can't. You can't change this property after you've landed a plane. Which is why your rspec test is failing because you're trying to override the weather to return true, but it's already set so it doesn't do anything.

i modified the rspec test to illustrate this

```
it 'delays a flight if weather is stormy' do
        allow(weather).to receive(:stormy?).and_return(true)
        p weather
        airport = Airport.new(weather: weather)
        p airport
        expect{airport.take_off(plane)}.to raise_error('Your flight has been delayed due to a storm')
end
```

the p statements will show up in your terminal when you run rspec, and you should see that airport now has a `@storm` set to true, but there are no planes to take off so no exception is raised.

In order to solve this, I'd try to wait until the last possible moment to call `Weather.new`, or create a setter method so you can set the `@storm` attribute when you need it

Hopefully this makes sense. Let me know if you have any questions
