### ISSUE TITLE
Challenge 17 - issues

### ISSUE THREAD

**Issue by valogopedina** [makersacademy/slack-overflow#175]
I'm struggling all day with this problem. Running git push heroku master, it could not work and I tried to create a new heroku app and calling that using git push heroku day-four:master and it worked. Now trying to run  heroku run rake db:auto_upgrade, I had this error:
Running rake db:auto_upgrade on bookmark1-app... up, run.6794
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

 After that When I tried to push heroku day-four:master I had the same error I had this morning: 
git push heroku day-four:master
To https://git.heroku.com/bookmark1-app.git
 ! [rejected]        day-four -> master (non-fast-forward)
error: failed to push some refs to 'https://git.heroku.com/bookmark1-app.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I also tried to pull origin master as suggested in the terminal (finding confirm with may pair and on goggle) but now I have some merging conflicts.

Anyone knows how to figure it out?

**Comment by ptolemybarnes** [comment]
Hey there,

1. Rake issue.

Did you create a Rakefile, defining the rake task `db:auto_upgrade`?

2. Heroku issue. 

This is the important message: `hint: Updates were rejected because a pushed branch tip is behind its remote`. Judging from your branch names "day-four", I would guess this is because the branch you're on is a branch off of an historical commit on master. If you provide the `-f` (force) flag when you push to heroku, it should go through successfully. Be careful with this command though as you're effectively overwriting what's on the remote with your local branch.

**Comment by valogopedina** [comment]
Yes, I did! I created the Rakefile defining db:auto_upgrade and I figured out the issue with git push -f.
Thanks for your help!
